version: '3.7'
services:
  steeltoe-app:
    container_name: steeltoe-app
    build:
      context: C:\Users\pivotal\source\Grafana_Observability
    ports:
    - 80:80
  zipkin:
    image: openzipkin/zipkin-slim
    container_name: zipkin
    ports:
    - 9411:9411
    depends_on:
      - steeltoe-app
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    #- --log.level=info
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - steeltoe-app
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
    - 8086:8086
    depends_on:
    - steeltoe-app
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
    - 9273:9273
    command:
    - --config=/etc/telegraf/telegraf.conf
    volumes:
    - ./telegraf:/etc/default/telegraf:ro
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
    - influxdb
    - prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000
    volumes:
    - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    - ./dashboard.json:/var/lib/grafana/dashboards/steeltoe.json:ro
    - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
    depends_on:
    - telegraf